// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Model;

namespace WebAPI.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    partial class EmployeeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Model.Dependent", b =>
                {
                    b.Property<int>("DependentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("date");

                    b.Property<string>("DependentFirstName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("DependentLastName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("DependentSSN")
                        .HasColumnName("DependentSSN")
                        .HasColumnType("varchar(9)")
                        .HasMaxLength(9)
                        .IsUnicode(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DependentId")
                        .HasName("PK__Dependen__9BC67CF1B2EA84BA");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            DependentId = 1,
                            DateCreated = new DateTime(2022, 3, 26, 22, 23, 24, 30, DateTimeKind.Local).AddTicks(8357),
                            DateOfBirth = new DateTime(1974, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2022, 3, 26, 22, 23, 24, 34, DateTimeKind.Local).AddTicks(4250),
                            DependentFirstName = "Evelyn",
                            DependentLastName = "Abbott",
                            DependentSSN = "222222222",
                            EmployeeId = 1
                        },
                        new
                        {
                            DependentId = 2,
                            DateCreated = new DateTime(2022, 3, 26, 22, 23, 24, 34, DateTimeKind.Local).AddTicks(5045),
                            DateOfBirth = new DateTime(2010, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2022, 3, 26, 22, 23, 24, 34, DateTimeKind.Local).AddTicks(5065),
                            DependentFirstName = "Noah",
                            DependentLastName = "Abbott",
                            DependentSSN = "777777777",
                            EmployeeId = 1
                        },
                        new
                        {
                            DependentId = 3,
                            DateCreated = new DateTime(2022, 3, 26, 22, 23, 24, 34, DateTimeKind.Local).AddTicks(5088),
                            DateOfBirth = new DateTime(1914, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2022, 3, 26, 22, 23, 24, 34, DateTimeKind.Local).AddTicks(5091),
                            DependentFirstName = "Maria",
                            DependentLastName = "Trapp",
                            DependentSSN = "333333333",
                            EmployeeId = 2
                        });
                });

            modelBuilder.Entity("WebAPI.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("EmployeeSSN")
                        .HasColumnName("EmployeeSSN")
                        .HasColumnType("varchar(9)")
                        .HasMaxLength(9)
                        .IsUnicode(false);

                    b.Property<bool?>("IsTerminated")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F113516F170");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateCreated = new DateTime(2022, 3, 26, 22, 23, 24, 36, DateTimeKind.Local).AddTicks(8992),
                            DateUpdated = new DateTime(2022, 3, 26, 22, 23, 24, 36, DateTimeKind.Local).AddTicks(9356),
                            EmployeeFirstName = "Lee",
                            EmployeeLastName = "Abbott",
                            EmployeeSSN = "999999999",
                            IsTerminated = false
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateCreated = new DateTime(2022, 3, 26, 22, 23, 24, 36, DateTimeKind.Local).AddTicks(9999),
                            DateUpdated = new DateTime(2022, 3, 26, 22, 23, 24, 37, DateTimeKind.Local).AddTicks(25),
                            EmployeeFirstName = "Georg",
                            EmployeeLastName = "Trapp",
                            EmployeeSSN = "555555555",
                            IsTerminated = false
                        });
                });

            modelBuilder.Entity("WebAPI.Model.Dependent", b =>
                {
                    b.HasOne("WebAPI.Model.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Dependent__Emplo__534D60F1")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
